export const CHANGE_BID_FORM = "CHANGE_BID_FORM";
export const CHANGE_BID_AMOUNT = "CHANGE_BID_AMOUNT";
export const POST_BID_ACTION = "POST_BID_ACTION";
export const UPDATE_AUCTIONS_STATE = "UPDATE_AUCTIONS_STATE";
export const CHANGE_AUCTION_DETAILS = "CHANGE_AUCTION_DETAILS";
export const CHANGE_SUBMIT_BUTTON_STATE = "CHANGE_SUBMIT_BUTTON_STATE";