export const GET_PATENTS = "GET_PATENTS";
export const SORT_PATENTS = "SORT_PATENTS"
export const CHANGE_PATENT_TYPE = "CHANGE_PATENT_TYPE"
export const CHANGE_PATENT_SUB_TYPE = "CHANGE_PATENT_SUB_TYPE"
export const CHANGE_PATENT_NAME = "CHANGE_PATENT_NAME"
export const CHANGE_COLLABORATORS = "CHANGE_COLLABORATORS"
export const CHANGE_FILE_NAME = "CHANGE_FILE_NAME"